// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://lnvfijcbfhvyumnhrkkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxudmZpamNiZmh2eXVtbmhya2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NTAwOTEsImV4cCI6MjA4NjUyNjA5MX0.iudXTS3YOZPS9k1OqdJbsCW7_j6GkPXG_R9qH0kivWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
